In [1]:
import numpy as np

In [3]:
from sklearn import preprocessing

In [9]:
data = np.array([[10,20,30],[5,6,7],[10000,5000,3000]],dtype=object)

In [10]:
data

array([[10, 20, 30],
       [5, 6, 7],
       [10000, 5000, 3000]], dtype=object)

In [12]:
data_normalised = preprocessing.normalize(data,norm='l1')

In [13]:
data_normalised

array([[0.16666667, 0.33333333, 0.5       ],
       [0.27777778, 0.33333333, 0.38888889],
       [0.55555556, 0.27777778, 0.16666667]])

In [14]:
data_normalised_l2 = preprocessing.normalize(data,norm='l2')

In [15]:
data_normalised_l2

array([[0.26726124, 0.53452248, 0.80178373],
       [0.47673129, 0.57207755, 0.66742381],
       [0.86386843, 0.43193421, 0.25916053]])