In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [15]:
np.arange(50,10,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12])

In [18]:
np.arange(0,16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
np.eye(50)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.45109917, 0.40551059, 0.92538924, 0.91561831, 0.05645799])

In [25]:
np.random.randint(5,10,20)

array([8, 8, 8, 9, 6, 9, 6, 5, 8, 9, 5, 9, 6, 5, 8, 7, 7, 9, 7, 7])

In [26]:
np.random.randn(5)

array([-0.04217499,  0.07589894, -1.64010226, -0.75314588,  0.93043368])

In [27]:
np.random.randn(5,5)

array([[-2.47204988, -0.45010113, -0.71997719,  2.8121248 , -0.46676505],
       [-0.01679752,  0.85035738,  0.1308715 , -1.00789602,  0.2253312 ],
       [ 0.46068982,  0.61535574, -0.09748536,  0.81488646, -0.99141727],
       [-0.40311257, -0.25948355,  0.28287522, -2.31128525,  1.78242928],
       [-0.45805201, -1.11349586,  1.81744568, -0.59140824, -0.91940739]])

In [31]:
np.arange(1,101).reshape(10,10)/10

array([[ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ],
       [ 1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ],
       [ 2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ],
       [ 3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ],
       [ 4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ],
       [ 5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ],
       [ 6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ],
       [ 7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ],
       [ 8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ],
       [ 9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. ]])

In [35]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [39]:
mat = np.arange(0,25).reshape(5,5)

In [40]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
mat[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [42]:
mat[2:,1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [45]:
mat[1:4,2:4]

array([[ 7,  8],
       [12, 13],
       [17, 18]])

In [46]:
mat.sum()

300

In [47]:
mat.std()

7.211102550927978

In [49]:
mat.sum(axis=0)

array([50, 55, 60, 65, 70])

In [50]:
mat.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [53]:
mat.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [56]:
x = np.array([[2,2],[3,4]])
y = np.array([[3,3],[2,5]])

In [57]:
x*y

array([[ 6,  6],
       [ 6, 20]])

In [58]:
x-y

array([[-1, -1],
       [ 1, -1]])

In [59]:
x+y

array([[5, 5],
       [5, 9]])

In [61]:
print(x/y)

[[0.66666667 0.66666667]
 [1.5        0.8       ]]
