In [8]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import numpy as np

In [11]:
digits = load_digits()

In [12]:
print('{}'.format(digits.data.shape))

(1797, 64)


In [13]:
print('{}'.format(digits.target.shape))

(1797,)


In [14]:
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.25,random_state=0)

In [23]:
logr = LogisticRegression(random_state=0)

In [24]:
logr.max_iter = 1797

In [33]:
loggr = logr.fit(x_test,y_test)

In [37]:
x_test[0].reshape(1,-1)

array([[ 0.,  0., 11., 16., 15.,  3.,  0.,  0.,  0.,  5., 16., 12., 11.,
        13.,  0.,  0.,  0.,  3., 13.,  1.,  5., 15.,  0.,  0.,  0.,  0.,
         0.,  0., 12., 11.,  0.,  0.,  0.,  0.,  0.,  1., 16.,  7.,  0.,
         0.,  0.,  0.,  0., 10., 15.,  0.,  0.,  0.,  0.,  0., 12., 16.,
        16., 11.,  1.,  0.,  0.,  0., 13., 13.,  8., 13., 16.,  8.]])

In [39]:
loggr.predict(x_test[0].reshape(1,-1))

array([2])

In [40]:
loggr.predict(x_test[0:10])

array([2, 8, 2, 6, 6, 7, 1, 9, 8, 5])

In [42]:
accuracy = loggr.score(x_test,y_test)

In [43]:
accuracy

1.0